version: '3.8'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  database:
    image: 'mysql:latest'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: movie
    ports:
      - '3306:3306'

volumes:
  redis:
